defmodule Mix.Tasks.Oma.Check do
  @shortdoc "Report WCAG contrast failures across the vendored themes"

  @moduledoc """
  Runs `Oma.Contrast` over the selected themes:

      mix oma.check [--tier builtin,community,extra] [--complete-only]
                    [--theme NAME] [--exceptions FILE] [--markdown FILE]

  Fails (exit 1) when a pair fails that is not listed in the exceptions
  file, one `theme fg/bg` per line, `#` comments allowed. The default file
  is `priv/themes/contrast_exceptions.txt`. `--markdown FILE` also writes
  the full report as a Markdown table.
  """

  use Mix.Task

  alias Oma.Contrast
  alias Oma.Themes

  @switches [
    tier: :string,
    complete_only: :boolean,
    theme: :keep,
    exceptions: :string,
    markdown: :string
  ]

  @impl true
  def run(args) do
    {opts, _, invalid} = OptionParser.parse(args, strict: @switches)
    if invalid != [], do: Mix.raise("unknown options: #{inspect(invalid)}")

    palettes = Themes.select(Mix.Tasks.Oma.Gen.select_opts(opts))
    exceptions = read_exceptions(opts[:exceptions] || "priv/themes/contrast_exceptions.txt")

    rows = for p <- palettes, r <- Contrast.report(p), do: {p, r}
    failures = for {p, r} <- rows, not r.pass?, do: {p, r}
    unexpected = for {p, r} <- failures, Contrast.key(p.name, r) not in exceptions, do: {p, r}

    failures
    |> Enum.group_by(fn {p, _} -> p.name end, fn {_, r} -> r end)
    |> Enum.sort()
    |> Enum.each(fn {name, rs} ->
      Mix.shell().info(name)

      Enum.each(rs, fn r ->
        flag = if Contrast.key(name, r) in exceptions, do: "  (known)", else: ""
        Mix.shell().info("  #{r.fg}/#{r.bg} #{r.ratio} < #{r.minimum}#{flag}")
      end)
    end)

    themes_failing = failures |> Enum.map(fn {p, _} -> p.name end) |> Enum.uniq() |> length()

    Mix.shell().info(
      "#{length(palettes)} themes, #{length(rows)} pairs, #{length(failures)} failing in #{themes_failing} themes, " <>
        "#{length(unexpected)} unexpected"
    )

    if opts[:markdown], do: write_markdown(opts[:markdown], palettes, rows, exceptions)

    if unexpected != [] do
      Mix.shell().error("contrast check failed")
      exit({:shutdown, 1})
    end
  end

  defp read_exceptions(path) do
    case File.read(path) do
      {:ok, body} ->
        body
        |> String.split("\n")
        |> Enum.map(&(&1 |> String.split("#", parts: 2) |> hd() |> String.trim()))
        |> Enum.reject(&(&1 == ""))
        |> MapSet.new()

      _ ->
        MapSet.new()
    end
  end

  defp write_markdown(path, palettes, rows, exceptions) do
    by_theme = Enum.group_by(rows, fn {p, _} -> p end, fn {_, r} -> r end)
    pairs = Contrast.pairs()

    header =
      "| Theme | Tier | Mode | Complete | " <>
        Enum.map_join(pairs, " | ", fn {fg, bg, min} -> "#{fg}/#{bg} ≥ #{min}" end) <> " |\n"

    sep = "|---|---|---|---|" <> String.duplicate("---:|", length(pairs)) <> "\n"

    body =
      Enum.map_join(palettes, "", fn p ->
        cells =
          Enum.map_join(by_theme[p], " | ", fn r ->
            cond do
              r.pass? -> "#{r.ratio}"
              Contrast.key(p.name, r) in exceptions -> "~~#{r.ratio}~~"
              true -> "**#{r.ratio}**"
            end
          end)

        "| #{p.name} | #{p.tier} | #{p.mode} | #{if p.complete?, do: "yes", else: "no"} | #{cells} |\n"
      end)

    failing = rows |> Enum.reject(fn {_, r} -> r.pass? end)

    summary = """
    # Contrast report

    Generated by `mix oma.check --markdown`. Bold ratios fail their minimum;
    struck-through ratios fail but are listed in the exceptions file.

    | Themes | Pairs | Failing pairs | Themes with a failure |
    |---:|---:|---:|---:|
    | #{length(palettes)} | #{length(rows)} | #{length(failing)} | #{failing |> Enum.map(fn {p, _} -> p.name end) |> Enum.uniq() |> length()} |

    ## Failures by pair

    | Pair | Minimum | Failing themes |
    |---|---:|---:|
    #{Enum.map_join(pairs, "\n", fn {fg, bg, min} -> "| #{fg}/#{bg} | #{min} | #{Enum.count(failing, fn {_, r} -> r.fg == fg and r.bg == bg end)} |" end)}

    ## Every theme

    """

    File.write!(path, summary <> header <> sep <> body)
    Mix.shell().info("wrote #{path}")
  end
end
