mode = "dark"

accent = "#ff2fb3"
selection = "#202024"
muted = "#7d8581"

background = "#0c0b0d"
dark_background = "#080709"
darker_background = "#050406"
lighter_background = "#19181a"

foreground = "#d8d1cc"
dark_foreground = "#7d8581"
light_foreground = "#a9a6ab"
bright_foreground = "#e0e1e4"

red = "#ff4a78"
yellow = "#8f57ff"
orange = "#ff6f93"
green = "#f2f2ea"
cyan = "#53b1ca"
blue = "#6c70e0"
magenta = "#bd5cff"
brown = "#ac4313"

bright_red = "#ff6f93"
bright_yellow = "#a375ff"
bright_green = "#fefef6"
bright_cyan = "#8ac7d8"
bright_blue = "#9488ff"
bright_magenta = "#b985ff"
