accent = "#1fb1a5"

background = "#001e49"

foreground = "#eef1d7"
dark_foreground = "#3f74c0"
bright_foreground = "#eef1d7"

red = "#c24e13"
yellow = "#d2df6f"
green = "#5a9f72"
cyan = "#83f0f1"
blue = "#1fb1a5"
magenta = "#4b64fd"

bright_red = "#fba571"
bright_yellow = "#e1e1b3"
bright_green = "#88c0a0"
bright_cyan = "#d4fcfc"
bright_blue = "#b3cbff"
bright_magenta = "#8a8cff"
