mode = "dark"

accent = "#9bb0c2"
selection = "#121b33"
muted = "#51545e"

background = "#0a0f1c"
dark_background = "#070b14"
darker_background = "#05070d"
lighter_background = "#121b33"

foreground = "#d4d5d9"
dark_foreground = "#9ea0a9"
light_foreground = "#dfe0e3"
bright_foreground = "#efeff1"

red = "#869aac"
yellow = "#9fadb8"
orange = "#92a3b2"
green = "#95a8b8"
cyan = "#b8c7d0"
blue = "#9bb0c2"
magenta = "#a8b9c6"
brown = "#4e5b6b"

bright_red = "#869aac"
bright_yellow = "#9fadb8"
bright_green = "#95a8b8"
bright_cyan = "#b8c7d0"
bright_blue = "#9bb0c2"
bright_magenta = "#a8b9c6"
