mode = "dark"

accent = "#d6a06b"
selection = "#514838"
muted = "#968872"

background = "#3a332a"
dark_background = "#2e2820"
darker_background = "#241f19"
lighter_background = "#463e33"

foreground = "#f5ecd9"
dark_foreground = "#b0a48f"
light_foreground = "#faf2e0"
bright_foreground = "#fff6e2"

red = "#ed806b"
yellow = "#dab46b"
orange = "#e08f53"
green = "#83baa1"
cyan = "#7dbebf"
blue = "#74accf"
magenta = "#c494b9"
brown = "#bd966e"

bright_red = "#ee9881"
bright_yellow = "#ebd493"
bright_green = "#a0cdb7"
bright_cyan = "#98d2d3"
bright_blue = "#93c2e2"
bright_magenta = "#d5afca"
