mode = "dark"

accent = "#e78a4e"
selection = "#45403d"
muted = "#928374"

background = "#282828"
dark_background = "#1b1b1b"
darker_background = "#141414"
lighter_background = "#32302f"

foreground = "#d4be98"
dark_foreground = "#7c6f64"
light_foreground = "#a89984"
bright_foreground = "#ddc7a1"

red = "#ea6962"
yellow = "#d8a657"
orange = "#e78a4e"
green = "#a9b665"
cyan = "#89b482"
blue = "#7daea3"
magenta = "#d3869b"
brown = "#744527"

bright_red = "#ea6962"
bright_yellow = "#d8a657"
bright_green = "#a9b665"
bright_cyan = "#89b482"
bright_blue = "#7daea3"
bright_magenta = "#d3869b"
