accent = "#6e29ad"

background = "#241b30"

foreground = "#f2f2e3"
dark_foreground = "#7f7094"
bright_foreground = "#f2f2e3"

red = "#e60a70"
yellow = "#adad3e"
green = "#00986c"
cyan = "#00b0b1"
blue = "#6e29ad"
magenta = "#b300ad"

bright_red = "#e60a70"
bright_yellow = "#f9f972"
bright_green = "#0ae4a4"
bright_cyan = "#00fbfd"
bright_blue = "#aa54f9"
bright_magenta = "#ff00f6"
