mode = "dark"

accent = "#a69f96"
selection = "#2f3e4a"
muted = "#6b706f"

background = "#232e37"
dark_background = "#1f2931"
darker_background = "#1b242b"
lighter_background = "#2f3e4a"

foreground = "#f0ead6"
dark_foreground = "#d5c48b"
light_foreground = "#f5f2e5"
bright_foreground = "#fefdfb"

red = "#e17f47"
yellow = "#f0ead6"
orange = "#e8b48e"
green = "#7e8b56"
cyan = "#80c0c0"
blue = "#a69f96"
magenta = "#c080c0"
brown = "#8b5b40"

bright_red = "#ff9966"
bright_yellow = "#ffffcc"
bright_green = "#9acd32"
bright_cyan = "#e0ffff"
bright_blue = "#add8e6"
bright_magenta = "#ffb6c1"
