mode = "light"

accent = "#0a0a0a"
selection = "#f7f7f7"
muted = "#919191"

background = "#ffffff"
dark_background = "#f2f2f2"
darker_background = "#e6e6e6"
lighter_background = "#f7f7f7"

foreground = "#0a0a0a"
dark_foreground = "#565656"
light_foreground = "#000000"
bright_foreground = "#000000"

red = "#0a0a0a"
yellow = "#0a0a0a"
orange = "#0a0a0a"
green = "#0a0a0a"
cyan = "#0a0a0a"
blue = "#0a0a0a"
magenta = "#0a0a0a"
brown = "#606060"

bright_red = "#0a0a0a"
bright_yellow = "#0a0a0a"
bright_green = "#0a0a0a"
bright_cyan = "#0a0a0a"
bright_blue = "#0a0a0a"
bright_magenta = "#0a0a0a"
