mode = "dark"

accent = "#c87d2a"
selection = "#6b5650"
muted = "#a58c82"

background = "#292025"
dark_background = "#1f181c"
darker_background = "#151013"
lighter_background = "#362d30"

foreground = "#fff4d8"
dark_foreground = "#a58c82"
light_foreground = "#fff4d8"
bright_foreground = "#fffaf0"

red = "#cf7358"
yellow = "#c8964b"
orange = "#c8964b"
green = "#9fad68"
cyan = "#9eb8b2"
blue = "#c87d2a"
magenta = "#c98c97"
brown = "#644b26"

bright_red = "#e58a70"
bright_yellow = "#e4c56d"
bright_green = "#b9c97f"
bright_cyan = "#c2d5d0"
bright_blue = "#df9850"
bright_magenta = "#ddb0b8"
